#----------------------------------------------------------------------------
# Cone membership
#----------------------------------------------------------------------------
#
# With an extra coordinate for the constant term, the condition above says
# that the target t = (v, v0) lies in the convex cone generated by the
# columns g_j = (a_j, b_j) and the slack column (0, 1). By Farkas' lemma
# exactly one of the following holds:
#
#   TRUE:   t = Σ y_j g_j  with  y >= 0           (a proof)
#   FALSE:  z·g_j <= 0 for all j,  and  z·t > 0    (a counterexample)
#
# Both certificates are computed in floating point by non-negative least
# squares: the projection of t onto the cone gives y, its residual z. They
# are then verified in exact rational arithmetic. Only if the verification
# fails, the exact simplex method decides (which is much slower for many
# variables, as these LPs are highly degenerate).

const SparseCol = Vector{Pair{Int,Coef}}

# Number of times the exact simplex method had to decide (for testing).
const SIMPLEX_FALLBACKS = Ref(0)

# Homogenized columns and target. Coordinates: subset bitmask S -> S (for
# S = 1..D-1), constant term -> D.
function homogenize(gens::Vector{Generator}, nvars::Int, v::Dict{Int,Coef})
    D = 1 << nvars
    cols = SparseCol[]
    for g in gens
        c = copy(g.a)
        iszero(g.b) || push!(c, D => g.b)
        push!(cols, c)
    end
    push!(cols, [D => one(Coef)])                   # slack: 1 >= 0
    t = SparseCol([(k == 0 ? D : k) => x for (k, x) in v if !iszero(x)])
    return D, cols, t
end

sdot(c::SparseCol, z::AbstractVector) = sum(x * z[k] for (k, x) in c; init=zero(eltype(z)))

function todense(::Type{T}, c::SparseCol, D) where {T}
    x = zeros(T, D)
    for (k, v) in c
        x[k] += T(v)
    end
    return x
end

# TRUE certificate: exact non-negative y with  Σ_{j in support} y_j g_j = t,
# as a vector over all columns. `nothing` if the support does not yield one.
function certify_true(cols, t, support)
    S = findall(support)
    rows = sort!(unique!([k for j in S for (k, _) in cols[j]] ∪ first.(t)))
    index = Dict(k => i for (i, k) in enumerate(rows))
    M = zeros(Coef, length(rows), length(S))
    for (c, j) in enumerate(S), (k, x) in cols[j]
        M[index[k], c] += x
    end
    rhs = zeros(Coef, length(rows))
    for (k, x) in t
        rhs[index[k]] += x
    end
    y = exact_solve(M, rhs)
    (y === nothing || any(<(0), y)) && return nothing
    full = zeros(Coef, length(cols))
    full[S] .= y
    return full
end

# FALSE certificate: exact z with  z·g_j <= 0  for all columns and  z·t > 0,
# obtained from the floating point residual r. Rounding r to integers can
# break tight constraints, which is repaired by
#   - shifting z by a multiple of a vector w with  w·g < 0  for all
#     elemental inequalities (w = -h for the polymatroid h(S) = f(|S|) with
#     f(k) = k(2n+1-k) strictly increasing and concave), and
#   - projecting z onto the subspace orthogonal to the equality constraints
#     and the other non-elemental columns that are tight at r (which the
#     shift does not help with).
function certify_false(cols, lines, t, r, nvars, D)
    f(k) = k * (2nvars + 1 - k)
    w = [BigInt(-f(count_ones(S))) for S in 1:D-1]
    push!(w, BigInt(-1))
    scale = 2.0^50 / maximum(abs, r)
    zr = [BigInt(round(x * scale)) for x in r]
    nel = count_elemental(nvars)
    tight = [j for j in nel+1:length(cols)
             if j ∉ lines && sdot(cols[j], r) >= -1e-9 * norm(r)]
    proj = [lines; tight]
    E = isempty(proj) ? nothing :
        reduce(hcat, [todense(Coef, cols[j], D) for j in proj])
    shift = BigInt(0)
    while shift <= BigInt(2)^30
        z = Coef.(zr .+ shift .* w)
        if E !== nothing
            # z -= E λ  with  EᵀE λ = Eᵀz  (any solution gives the projection)
            λ = exact_solve(E' * E, E' * z)
            z .-= E * λ
        end
        sdot(t, z) > 0 || return nothing
        all(c -> sdot(c, z) <= 0, cols) && return z
        shift = iszero(shift) ? BigInt(1) : 2shift
    end
    return nothing
end

# FALSE certificate, computed exactly: the residual of the projection of t
# onto the span of the passive columns of the least squares solution. Costs
# O(k^3) rational operations for k passive columns.
function certify_false_exact(cols, t, passive, D)
    AP = reduce(hcat, [todense(Coef, cols[j], D) for j in findall(passive)])
    tt = todense(Coef, t, D)
    y = exact_solve(AP' * AP, AP' * tt)
    z = tt - AP * y
    return sdot(t, z) > 0 && all(c -> sdot(c, z) <= 0, cols) ? z : nothing
end

"""
    decide(gens, nvars, v; method=:auto) -> (verdict, certificate)

Is  `v·h + v[0] >= 0`  implied by the generators?

The certificate is a vector `y >= 0` of multipliers over the columns
(`= [gens; slack]`) when the verdict is `true`, a vector `z` with
`z·g <= 0` for every column and `z·t > 0` when it is `false`, and
`nothing` when the exact simplex method had to decide. Certificates are
always verified in exact arithmetic before they are returned.

`method=:simplex` skips the least squares method (and thus produces no
certificate); it is much slower for more than about 7 variables.
"""
function decide(gens::Vector{Generator}, nvars::Int, v::Dict{Int,Coef};
                method::Symbol=:auto)
    if method == :auto
        D, cols, t = homogenize(gens, nvars, v)
        A = reduce(hcat, [todense(Float64, c, D) for c in cols])
        b = todense(Float64, t, D)
        res = nnls(A, b)
        if res !== nothing
            x, passive = res
            r = b - A * x
            if norm(r) <= 1e-8 * max(1.0, norm(b))
                y = certify_true(cols, t, passive)
                y === nothing || return true, y
            else
                lines = [j for (j, g) in enumerate(gens) if g.line]
                z = certify_false(cols, lines, t, r, nvars, D)
                # the exact projection costs O(k^3) rational operations for k
                # passive columns, which is where the seconds go when a
                # statement at eight variables cannot be proven. The simplex
                # is sometimes quicker on those, but only sometimes, and it
                # is the provable case that it cannot do at all.
                z === nothing && (z = certify_false_exact(cols, t, passive, D))
                z === nothing || return false, z
            end
        end
        SIMPLEX_FALLBACKS[] += 1
    end
    # Machine-size rationals are checked for overflow; fall back to BigInt.
    verdict = try
        implied_simplex(Rational{Int}, gens, nvars, v)
    catch e
        e isa Union{OverflowError,InexactError} || rethrow()
        implied_simplex(Coef, gens, nvars, v)
    end
    return verdict, nothing
end

"""
    implied(gens, nvars, v; method=:auto) -> Bool

Is  `v·h + v[0] >= 0`  implied by the generators? See [`decide`](@ref).
"""
implied(gens, nvars, v; kw...) = first(decide(gens, nvars, v; kw...))

# Solve the LP from the comment above with the simplex method.
function implied_simplex(::Type{T}, gens::Vector{Generator}, nvars::Int,
                         v::Dict{Int,Coef}) where {T}
    m = (1 << nvars) - 1
    A = zeros(T, m, length(gens))
    for (j, g) in enumerate(gens), (k, x) in g.a
        A[k, j] += T(x)
    end
    rhs = zeros(T, m)
    for (k, x) in v
        k != 0 && (rhs[k] = T(x))
    end
    cost = T[T(g.b) for g in gens]
    status, value = simplex(A, rhs, cost)
    status == :infeasible && return false
    status == :unbounded && return true
    return value <= T(get(v, 0, zero(Coef)))
end

"""
    simplify_certificate(gens, nvars, v, z, D) -> z

Replace a Farkas certificate by an equivalent one with smaller numbers:
round the entropies it implies to a small common denominator and verify the
result exactly, then cancel the common factor. Returns `z` itself if no
rounding verifies.
"""
function simplify_certificate(gens, nvars, v, z, D)
    _, cols, t = homogenize(gens, nvars, v)
    valid(c) = sdot(t, c) > 0 && all(col -> sdot(col, c) <= 0, cols)
    grid = (1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 24, 32, 64, 128, 1024)
    s = -z[D]
    if s > 0
        # A point: the constant term fixes the scale, so only round.
        h = -z[1:D-1] ./ s
        for d in grid
            cand = Coef[-round(BigInt, x * d) for x in h]
            push!(cand, Coef(-d))
            valid(cand) && return cancel_factor(cand)
        end
    else
        # A direction: it may be scaled freely, so round it coarsely and add
        # a strictly interior polymatroid to absorb the rounding error.
        peak = maximum(abs, z[1:D-1]; init=zero(Coef))
        iszero(peak) && return cancel_factor(z)
        f(k) = k * (2nvars + 1 - k)
        for m in grid
            # entropies h = -z, rounded and shifted; the candidate is -h
            cand = Coef[-(round(BigInt, -x * m // peak) + f(count_ones(S)))
                        for (S, x) in enumerate(z[1:D-1])]
            push!(cand, zero(Coef))
            valid(cand) && return cancel_factor(cand)
        end
    end
    return cancel_factor(z)
end

# Scale a vector of rationals to coprime integers (a positive scaling, which
# changes neither the Farkas conditions nor the entropies it implies).
function cancel_factor(c::Vector{Coef})
    ints = numerator.(c .* lcm(denominator.(c)))
    g = gcd(ints)
    return iszero(g) ? c : Coef.(ints .÷ g)
end
