#----------------------------------------------------------------------------
# Exporting a proof to Lean 4
#----------------------------------------------------------------------------
#
# A proof here is already the thing a formal proof needs: the statement
# written as a non-negative combination of inequalities, with exact rational
# multipliers. Turning that into Lean is therefore not a search, it is a
# transcription, and `linarith` closes the goal because the combination is
# the one it would have to find.
#
# The export is in two layers, which keeps the generated part checkable on
# its own:
#
#   * the arithmetic core, generated here: one real variable per joint
#     entropy, the inequalities used as hypotheses, and the statement as the
#     goal. It needs nothing but Mathlib's linarith, and says exactly what
#     this package proved -- that the statement follows from those
#     inequalities by linear arithmetic.
#
#   * the bridge, written once by hand against a library that defines
#     entropy (PFR, or LeanInfoTheory), which instantiates those variables
#     with real entropies and discharges each hypothesis from the library's
#     nonnegativity lemmas. See docs/src/lean.md.
#
# Splitting them is not a dodge: the first layer is where a transcription
# bug would live, and it is the layer a machine can check without a
# multi-gigabyte dependency.

"""
    lean(lines...; theorem="xitip_proof", imports=true) -> String

The Lean 4 source of the arithmetic core of a proof: one real variable per
joint entropy, one hypothesis per inequality the proof uses, the statement
as the goal, and `linarith` to close it.

The statement must be provable. What comes back is checked by Lean, not by
this package — see [Formal proof in Lean](@ref) for what the core does and
does not say, and for the bridge that gives its variables their meaning.

```jldoctest
julia> print(lean("H(X,Y,Z) <= H(X,Y) + H(Z)"; imports=false))
/-
  H(X,Y,Z) <= H(X,Y) + H(Z)

  Generated by Xitip.jl. Every hypothesis is an elemental inequality;
  the goal is the statement with everything moved to one side.
-/
theorem xitip_proof
    (h_Y h_X_Y h_Y_Z h_X_Y_Z h_Z : ℝ)
    -- I(X;Z|Y) >= 0
    (e1 : 0 ≤ -h_Y + h_X_Y + h_Y_Z - h_X_Y_Z)
    -- I(Y;Z) >= 0
    (e2 : 0 ≤ h_Y + h_Z - h_Y_Z)
    : 0 ≤ h_X_Y + h_Z - h_X_Y_Z := by
  linarith
```
"""
lean(lines::AbstractString...; kw...) = lean(collect(lines); kw...)

function lean(lines::AbstractVector{<:AbstractString};
              theorem::AbstractString="xitip_proof", imports::Bool=true,
              method::Symbol=:auto)
    result = explain(lines; method=method)
    result.verdict ||
        throw(XitipError("only a provable statement can be exported; this " *
                         "one has a counterexample"))
    proofs = [c for c in result.certificates if c isa Proof]
    isempty(proofs) &&
        throw(XitipError("no proof to export, the verdict having come from " *
                         "the simplex fallback"))
    stmts, sources = parse_statements(lines)
    P = Problem(stmts, sources)
    names = P.var_names

    out = IOBuffer()
    # the whole of Mathlib, which costs a few seconds to import but does not
    # go stale as module paths are rearranged between versions
    imports && println(out, "import Mathlib\n")
    for (k, proof) in pairs(proofs)
        k == 1 || println(out)
        label = length(proofs) == 1 ? theorem : "$(theorem)_$(k)"
        lean_theorem(out, proof, names, lines, label)
    end
    return String(take!(out))
end

function lean_theorem(out::IO, proof::Proof, names, lines, label)
    # the coefficients come off the certificate itself, not off its printed
    # form: the printer writes a half as "1/2", which the grammar does not read
    goal = proof.coefficients
    used = [(step, step.quantity) for step in proof.steps]

    # one real variable per joint entropy anything mentions, in the order
    # they are first seen, so the signature reads like the proof
    order = Int[]
    for coefs in [last.(used); [goal]], mask in sort(collect(keys(coefs)))
        mask != 0 && !(mask in order) && push!(order, mask)
    end
    variable = Dict(mask => "h_" * join(setnames(mask, names), "_")
                    for mask in order)

    println(out, "/-")
    for line in lines
        println(out, "  ", line)
    end
    println(out, """

  Generated by Xitip.jl. Every hypothesis is an elemental inequality;
  the goal is the statement with everything moved to one side.
-/""")
    println(out, "theorem ", label)
    # an identity mentions no entropies at all, and then there is no binder
    isempty(order) ||
        println(out, "    (", join((variable[m] for m in order), " "), " : ℝ)")
    for (k, (step, coefs)) in pairs(used)
        # a constraint's text already carries its own relation; an elemental
        # inequality is bare, so it gets one
        println(out, "    -- ", isempty(step.source) ?
                     step.name * " " * step.justification : step.source)
        println(out, "    (e", k, " : 0 ≤ ", lean_expression(coefs, variable),
                ")")
    end
    println(out, "    : 0 ≤ ", lean_expression(goal, variable), " := by")
    println(out, "  linarith")
end

"""The names of the variables in a subset, in index order."""
setnames(mask::Int, names) =
    [names[i] for i in 1:length(names) if mask & (1 << (i - 1)) != 0]

"""A linear combination of entropy variables, as Lean source."""
function lean_expression(coefs::AbstractDict, variable)
    parts = String[]
    for mask in sort(collect(keys(coefs)))
        c = coefs[mask]
        iszero(c) && continue
        sign = c < 0 ? "-" : (isempty(parts) ? "" : "+")
        size = abs(c)
        term = mask == 0 ? lean_number(size) :
               isone(size) ? variable[mask] :
               lean_number(size) * " * " * variable[mask]
        push!(parts, isempty(parts) ? (c < 0 ? "-" * term : term) :
                     sign * " " * term)
    end
    isempty(parts) && return "(0 : ℝ)"
    return join(parts, " ")
end

"""A rational as Lean source, kept exact."""
lean_number(c) = isone(denominator(c)) ? string(numerator(c)) :
                 "(" * string(numerator(c)) * "/" * string(denominator(c)) * " : ℝ)"
